import 'package:demo_acbrpixcd_flutter/plugin/acbrpixcd_plugin.dart';
import 'package:demo_acbrpixcd_flutter/ui/pages/config/configuracoes_pixcd_page.dart';
import 'package:demo_acbrpixcd_flutter/ui/pages/config/psp_config_form.dart';
import 'package:demo_acbrpixcd_flutter/ui/widgets/drawer_tab_scaffold.dart';
import 'package:flutter/material.dart';

class ConfiguracoesRootPage extends StatelessWidget {
  const ConfiguracoesRootPage({super.key, required this.plugin});

  final ACBrPixCDPlugin plugin;

  @override
  Widget build(BuildContext context) {
    final items = <DrawerTabItem>[
      const DrawerTabItem(title: 'Configurações PIXCD', icon: Icons.settings),
      const DrawerTabItem(title: 'Bradesco', icon: Icons.account_balance),
      const DrawerTabItem(title: 'Itau', icon: Icons.account_balance),
      const DrawerTabItem(title: 'Banco do Brasil', icon: Icons.account_balance),
      const DrawerTabItem(title: 'Santander', icon: Icons.account_balance),
      const DrawerTabItem(title: 'Shipay', icon: Icons.account_balance),
      const DrawerTabItem(title: 'Sicredi', icon: Icons.account_balance),
      const DrawerTabItem(title: 'Sicoob', icon: Icons.account_balance),
      const DrawerTabItem(title: 'PagSeguro', icon: Icons.account_balance),
      const DrawerTabItem(title: 'PixPDV', icon: Icons.account_balance),
      const DrawerTabItem(title: 'Inter', icon: Icons.account_balance),
      const DrawerTabItem(title: 'GerenciaNet', icon: Icons.account_balance),
      const DrawerTabItem(title: 'Ailos', icon: Icons.account_balance),
      const DrawerTabItem(title: 'Matera', icon: Icons.account_balance),
      const DrawerTabItem(title: 'Cielo', icon: Icons.account_balance),
      const DrawerTabItem(title: 'MercadoPago', icon: Icons.account_balance),
      const DrawerTabItem(title: 'C6Bank', icon: Icons.account_balance),
      const DrawerTabItem(title: 'AppLess', icon: Icons.account_balance),
      const DrawerTabItem(title: 'QQPag', icon: Icons.account_balance),
    ];

    final pages = <Widget>[
      ConfiguracoesPixCDPage(plugin: plugin),
      PspConfigForm(
        plugin: plugin,
        sessao: 'Bradesco',
        fields: const [
          ConfigFieldDef(keyName: 'ChavePIX', label: 'Chave PIX'),
          ConfigFieldDef(keyName: 'ClientID', label: 'ClientID'),
          ConfigFieldDef(keyName: 'ClientSecret', label: 'ClientSecret'),
          ConfigFieldDef(
            keyName: 'ArqPFX',
            label: 'ArqPFX',
            isFilePicker: true,
            pickerTitle: 'Selecione um arquivo PFX',
            suggestedFileName: 'certificado.pfx',
            mimeTypes: ['application/x-pkcs12', 'application/octet-stream'],
          ),
          ConfigFieldDef(keyName: 'SenhaPFX', label: 'SenhaPFX', obscureText: true),
          ConfigFieldDef(keyName: 'Scopes', label: 'Scopes'),
        ],
      ),
      PspConfigForm(
        plugin: plugin,
        sessao: 'Itau',
        fields: const [
          ConfigFieldDef(keyName: 'ChavePIX', label: 'Chave PIX'),
          ConfigFieldDef(keyName: 'ClientID', label: 'ClientID'),
          ConfigFieldDef(keyName: 'ClientSecret', label: 'ClientSecret'),
          ConfigFieldDef(
            keyName: 'ArqChavePrivada',
            label: 'ArqChavePrivada',
            isFilePicker: true,
            pickerTitle: 'Selecione um arquivo KEY',
            suggestedFileName: 'certificado.key',
            mimeTypes: ['application/octet-stream', 'text/plain'],
          ),
          ConfigFieldDef(
            keyName: 'ArqCertificado',
            label: 'ArqCertificado',
            isFilePicker: true,
            pickerTitle: 'Selecione um arquivo PEM',
            suggestedFileName: 'certificado.pem',
            mimeTypes: ['application/x-pem-file', 'application/octet-stream', 'text/plain'],
          ),
          ConfigFieldDef(keyName: 'Scopes', label: 'Scopes'),
        ],
      ),
      PspConfigForm(
        plugin: plugin,
        sessao: 'BancoBrasil',
        fields: const [
          ConfigFieldDef(keyName: 'ChavePIX', label: 'Chave PIX'),
          ConfigFieldDef(keyName: 'ClientID', label: 'ClientID'),
          ConfigFieldDef(keyName: 'ClientSecret', label: 'ClientSecret'),
          ConfigFieldDef(keyName: 'DeveloperApplicationKey', label: 'DeveloperApplicationKey'),
          ConfigFieldDef(
            keyName: 'ArqChavePrivada',
            label: 'ArqChavePrivada',
            isFilePicker: true,
            pickerTitle: 'Selecione um arquivo KEY',
            suggestedFileName: 'certificado.key',
            mimeTypes: ['application/octet-stream'],
          ),
          ConfigFieldDef(
            keyName: 'ArqCertificado',
            label: 'ArqCertificado',
            isFilePicker: true,
            pickerTitle: 'Selecione um arquivo PEM',
            suggestedFileName: 'certificado.pem',
            mimeTypes: ['application/x-pem-file', 'application/octet-stream', 'text/plain'],
          ),
          ConfigFieldDef(
            keyName: 'ArqPFX',
            label: 'ArqPFX',
            isFilePicker: true,
            pickerTitle: 'Selecione um arquivo PFX',
            suggestedFileName: 'certificado.pfx',
            mimeTypes: ['application/x-pkcs12', 'application/octet-stream'],
          ),
          ConfigFieldDef(keyName: 'SenhaPFX', label: 'SenhaPFX', obscureText: true),
          ConfigFieldDef(keyName: 'BBAPIVersao', label: 'BBAPIVersao', keyboardType: TextInputType.number),
          ConfigFieldDef(keyName: 'Scopes', label: 'Scopes'),
        ],
      ),
      PspConfigForm(
        plugin: plugin,
        sessao: 'Santander',
        fields: const [
          ConfigFieldDef(keyName: 'ChavePIX', label: 'Chave PIX'),
          ConfigFieldDef(keyName: 'ConsumerKey', label: 'ConsumerKey'),
          ConfigFieldDef(keyName: 'ConsumerSecret', label: 'ConsumerSecret'),
          ConfigFieldDef(
            keyName: 'ArqCertificadoPFX',
            label: 'ArqCertificadoPFX',
            isFilePicker: true,
            pickerTitle: 'Selecione um arquivo PFX',
            suggestedFileName: 'certificado.pfx',
            mimeTypes: ['application/x-pkcs12', 'application/octet-stream'],
          ),
          ConfigFieldDef(keyName: 'SenhaCertificadoPFX', label: 'SenhaCertificadoPFX', obscureText: true),
          ConfigFieldDef(keyName: 'Scopes', label: 'Scopes'),
        ],
      ),
      PspConfigForm(
        plugin: plugin,
        sessao: 'Shipay',
        fields: const [
          ConfigFieldDef(keyName: 'ClientID', label: 'ClientID'),
          ConfigFieldDef(keyName: 'SecretKey', label: 'SecretKey'),
          ConfigFieldDef(keyName: 'AccessKey', label: 'AccessKey'),
          ConfigFieldDef(keyName: 'Scopes', label: 'Scopes'),
        ],
      ),
      PspConfigForm(
        plugin: plugin,
        sessao: 'Sicredi',
        fields: const [
          ConfigFieldDef(keyName: 'ChavePIX', label: 'Chave PIX'),
          ConfigFieldDef(keyName: 'ClientID', label: 'ClientID'),
          ConfigFieldDef(keyName: 'ClientSecret', label: 'ClientSecret'),
          ConfigFieldDef(
            keyName: 'ArqChavePrivada',
            label: 'ArqChavePrivada',
            isFilePicker: true,
            pickerTitle: 'Selecione um arquivo KEY',
            suggestedFileName: 'certificado.key',
            mimeTypes: ['application/octet-stream'],
          ),
          ConfigFieldDef(
            keyName: 'ArqCertificado',
            label: 'ArqCertificado',
            isFilePicker: true,
            pickerTitle: 'Selecione um arquivo CER',
            suggestedFileName: 'certificado.cer',
            mimeTypes: ['application/x-x509-ca-cert', 'application/octet-stream'],
          ),
          ConfigFieldDef(keyName: 'Scopes', label: 'Scopes'),
        ],
      ),
      PspConfigForm(
        plugin: plugin,
        sessao: 'Sicoob',
        fields: const [
          ConfigFieldDef(keyName: 'ChavePIX', label: 'Chave PIX'),
          ConfigFieldDef(keyName: 'ClientID', label: 'ClientID'),
          ConfigFieldDef(keyName: 'TokenSandbox', label: 'TokenSandbox'),
          ConfigFieldDef(
            keyName: 'ArqChavePrivada',
            label: 'ArqChavePrivada',
            isFilePicker: true,
            pickerTitle: 'Selecione um arquivo KEY',
            suggestedFileName: 'certificado.key',
            mimeTypes: ['application/octet-stream'],
          ),
          ConfigFieldDef(
            keyName: 'ArqCertificado',
            label: 'ArqCertificado',
            isFilePicker: true,
            pickerTitle: 'Selecione um arquivo PEM',
            suggestedFileName: 'certificado.pem',
            mimeTypes: ['application/x-pem-file', 'application/octet-stream', 'text/plain'],
          ),
          ConfigFieldDef(keyName: 'Scopes', label: 'Scopes'),
        ],
      ),
      PspConfigForm(
        plugin: plugin,
        sessao: 'PagSeguro',
        fields: const [
          ConfigFieldDef(keyName: 'ChavePIX', label: 'Chave PIX'),
          ConfigFieldDef(keyName: 'ClientID', label: 'ClientID'),
          ConfigFieldDef(keyName: 'ClientSecret', label: 'ClientSecret'),
          ConfigFieldDef(
            keyName: 'ArqChavePrivada',
            label: 'ArqChavePrivada',
            isFilePicker: true,
            pickerTitle: 'Selecione um arquivo KEY',
            suggestedFileName: 'certificado.key',
            mimeTypes: ['application/octet-stream'],
          ),
          ConfigFieldDef(
            keyName: 'ArqCertificado',
            label: 'ArqCertificado',
            isFilePicker: true,
            pickerTitle: 'Selecione um arquivo PEM',
            suggestedFileName: 'certificado.pem',
            mimeTypes: ['application/x-pem-file', 'application/octet-stream', 'text/plain'],
          ),
          ConfigFieldDef(keyName: 'Scopes', label: 'Scopes'),
        ],
      ),
      PspConfigForm(
        plugin: plugin,
        sessao: 'PixPDV',
        fields: const [
          ConfigFieldDef(keyName: 'CNPJ', label: 'CNPJ'),
          ConfigFieldDef(keyName: 'Token', label: 'Token'),
          ConfigFieldDef(keyName: 'SecretKey', label: 'SecretKey'),
          ConfigFieldDef(keyName: 'Scopes', label: 'Scopes'),
        ],
      ),
      PspConfigForm(
        plugin: plugin,
        sessao: 'Inter',
        fields: const [
          ConfigFieldDef(keyName: 'ChavePIX', label: 'Chave PIX'),
          ConfigFieldDef(keyName: 'ClientID', label: 'ClientID'),
          ConfigFieldDef(keyName: 'ClientSecret', label: 'ClientSecret'),
          ConfigFieldDef(
            keyName: 'ArqChavePrivada',
            label: 'ArqChavePrivada',
            isFilePicker: true,
            pickerTitle: 'Selecione um arquivo KEY',
            suggestedFileName: 'certificado.key',
            mimeTypes: ['application/octet-stream'],
          ),
          ConfigFieldDef(
            keyName: 'ArqCertificado',
            label: 'ArqCertificado',
            isFilePicker: true,
            pickerTitle: 'Selecione um arquivo PEM',
            suggestedFileName: 'certificado.pem',
            mimeTypes: ['application/x-pem-file', 'application/octet-stream', 'text/plain'],
          ),
          ConfigFieldDef(keyName: 'Scopes', label: 'Scopes'),
        ],
      ),
      PspConfigForm(
        plugin: plugin,
        sessao: 'GerenciaNet',
        fields: const [
          ConfigFieldDef(keyName: 'ChavePIX', label: 'Chave PIX'),
          ConfigFieldDef(keyName: 'ClientID', label: 'ClientID'),
          ConfigFieldDef(keyName: 'ClientSecret', label: 'ClientSecret'),
          ConfigFieldDef(
            keyName: 'ArqPFX',
            label: 'ArqPFX',
            isFilePicker: true,
            pickerTitle: 'Selecione um arquivo p12',
            suggestedFileName: 'certificado.p12',
            mimeTypes: ['application/x-pkcs12', 'application/octet-stream'],
          ),
          ConfigFieldDef(keyName: 'Scopes', label: 'Scopes'),
        ],
      ),
      PspConfigForm(
        plugin: plugin,
        sessao: 'Ailos',
        fields: const [
          ConfigFieldDef(keyName: 'ChavePIX', label: 'Chave PIX'),
          ConfigFieldDef(keyName: 'ClientID', label: 'ClientID'),
          ConfigFieldDef(keyName: 'ClientSecret', label: 'ClientSecret'),
          ConfigFieldDef(
            keyName: 'ArqChavePrivada',
            label: 'ArqChavePrivada',
            isFilePicker: true,
            pickerTitle: 'Selecione um arquivo KEY',
            suggestedFileName: 'certificado.key',
            mimeTypes: ['application/octet-stream'],
          ),
          ConfigFieldDef(
            keyName: 'ArqCertificado',
            label: 'ArqCertificado',
            isFilePicker: true,
            pickerTitle: 'Selecione um arquivo PEM',
            suggestedFileName: 'certificado.pem',
            mimeTypes: ['application/x-pem-file', 'application/octet-stream', 'text/plain'],
          ),
          ConfigFieldDef(
            keyName: 'ArqCertificadoRoot',
            label: 'ArqCertificadoRoot',
            isFilePicker: true,
            pickerTitle: 'Selecione um arquivo CRT',
            suggestedFileName: 'certificado_root.crt',
            mimeTypes: ['application/x-x509-ca-cert', 'application/octet-stream'],
          ),
          ConfigFieldDef(keyName: 'Scopes', label: 'Scopes'),
        ],
      ),
      PspConfigForm(
        plugin: plugin,
        sessao: 'Matera',
        fields: const [
          ConfigFieldDef(keyName: 'ChavePIX', label: 'Chave PIX'),
          ConfigFieldDef(keyName: 'ClientID', label: 'ClientID'),
          ConfigFieldDef(keyName: 'SecretKey', label: 'SecretKey'),
          ConfigFieldDef(keyName: 'ClientSecret', label: 'ClientSecret'),
          ConfigFieldDef(
            keyName: 'ArqCertificado',
            label: 'ArqCertificado',
            isFilePicker: true,
            pickerTitle: 'Selecione um arquivo PEM',
            suggestedFileName: 'certificado.pem',
            mimeTypes: ['application/x-pem-file', 'application/octet-stream', 'text/plain'],
          ),
          ConfigFieldDef(
            keyName: 'ArqChavePrivada',
            label: 'ArqChavePrivada',
            isFilePicker: true,
            pickerTitle: 'Selecione um arquivo KEY',
            suggestedFileName: 'certificado.key',
            mimeTypes: ['application/octet-stream'],
          ),
          ConfigFieldDef(keyName: 'AccountID', label: 'AccountID'),
          ConfigFieldDef(keyName: 'MediatorFee', label: 'MediatorFee'),
          ConfigFieldDef(keyName: 'Scopes', label: 'Scopes'),
        ],
      ),
      PspConfigForm(
        plugin: plugin,
        sessao: 'Cielo',
        fields: const [
          ConfigFieldDef(keyName: 'ChavePIX', label: 'Chave PIX'),
          ConfigFieldDef(keyName: 'ClientID', label: 'ClientID'),
          ConfigFieldDef(keyName: 'ClientSecret', label: 'ClientSecret'),
          ConfigFieldDef(
            keyName: 'ArqChavePrivada',
            label: 'ArqChavePrivada',
            isFilePicker: true,
            pickerTitle: 'Selecione um arquivo KEY',
            suggestedFileName: 'certificado.key',
            mimeTypes: ['application/octet-stream'],
          ),
          ConfigFieldDef(
            keyName: 'ArqCertificado',
            label: 'ArqCertificado',
            isFilePicker: true,
            pickerTitle: 'Selecione um arquivo CER',
            suggestedFileName: 'certificado.cer',
            mimeTypes: ['application/x-x509-ca-cert', 'application/octet-stream'],
          ),
          ConfigFieldDef(keyName: 'Scopes', label: 'Scopes'),
        ],
      ),
      PspConfigForm(
        plugin: plugin,
        sessao: 'MercadoPago',
        fields: const [
          ConfigFieldDef(keyName: 'ChavePIX', label: 'Chave PIX'),
          ConfigFieldDef(keyName: 'AccessToken', label: 'AccessToken'),
          ConfigFieldDef(keyName: 'Scopes', label: 'Scopes'),
        ],
      ),
      PspConfigForm(
        plugin: plugin,
        sessao: 'C6Bank',
        fields: const [
          ConfigFieldDef(keyName: 'ChavePIX', label: 'Chave PIX'),
          ConfigFieldDef(keyName: 'ClientID', label: 'ClientID'),
          ConfigFieldDef(keyName: 'ClientSecret', label: 'ClientSecret'),
          ConfigFieldDef(
            keyName: 'ArqChavePrivada',
            label: 'ArqChavePrivada',
            isFilePicker: true,
            pickerTitle: 'Selecione um arquivo KEY',
            suggestedFileName: 'certificado.key',
            mimeTypes: ['application/octet-stream'],
          ),
          ConfigFieldDef(
            keyName: 'ArqCertificado',
            label: 'ArqCertificado',
            isFilePicker: true,
            pickerTitle: 'Selecione um arquivo PEM',
            suggestedFileName: 'certificado.pem',
            mimeTypes: ['application/x-pem-file', 'application/octet-stream', 'text/plain'],
          ),
          ConfigFieldDef(keyName: 'Scopes', label: 'Scopes'),
        ],
      ),
      PspConfigForm(
        plugin: plugin,
        sessao: 'AppLess',
        fields: const [
          ConfigFieldDef(keyName: 'ClientID', label: 'ClientID'),
          ConfigFieldDef(keyName: 'ClientSecret', label: 'ClientSecret'),
          ConfigFieldDef(keyName: 'SecretKeyHMAC', label: 'SecretKeyHMAC'),
          ConfigFieldDef(keyName: 'Scopes', label: 'Scopes'),
        ],
      ),
      PspConfigForm(
        plugin: plugin,
        sessao: 'QQPag',
        fields: const [
          ConfigFieldDef(keyName: 'ChavePIX', label: 'Chave PIX'),
          ConfigFieldDef(keyName: 'ClientID', label: 'ClientID'),
          ConfigFieldDef(keyName: 'ClientSecret', label: 'ClientSecret'),
          ConfigFieldDef(keyName: 'Scopes', label: 'Scopes'),
        ],
      ),
    ];

    return DrawerTabScaffold(items: items, pages: pages);
  }
}

