;;;;;;;;;;;;;; ENDERECOS DA NFGas ;;;;;;;;;;;;;;;;
[NFGas_AC_P]
Usar=NFGas_SVRS_P

[NFGas_AC_H]
Usar=NFGas_SVRS_H

[NFGas_AL_P]
Usar=NFGas_SVRS_P

[NFGas_AL_H]
Usar=NFGas_SVRS_H

[NFGas_AP_P]
Usar=NFGas_SVRS_P

[NFGas_AP_H]
Usar=NFGas_SVRS_H

[NFGas_AM_P]
Usar=NFGas_SVRS_P

[NFGas_AM_H]
Usar=NFGas_SVRS_H

[NFGas_BA_P]
Usar=NFGas_SVRS_P

[NFGas_BA_H]
Usar=NFGas_SVRS_H

[NFGas_CE_P]
Usar=NFGas_SVRS_P

[NFGas_CE_H]
Usar=NFGas_SVRS_H

[NFGas_DF_P]
Usar=NFGas_SVRS_P

[NFGas_DF_H]
Usar=NFGas_SVRS_H

[NFGas_ES_P]
Usar=NFGas_SVRS_P

[NFGas_ES_H]
Usar=NFGas_SVRS_H

[NFGas_GO_P]
Usar=NFGas_SVRS_P

[NFGas_GO_H]
Usar=NFGas_SVRS_H

[NFGas_MA_P]
Usar=NFGas_SVAN_P

[NFGas_MA_H]
Usar=NFGas_SVAN_H

[NFGas_MG_P]
Usar=NFGas_SVRS_P

[NFGas_MG_H]
Usar=NFGas_SVRS_H

[NFGas_MS_P]
Usar=NFGas_SVRS_P

[NFGas_MS_H]
Usar=NFGas_SVRS_H

[NFGas_MT_P]
Usar=NFGas_SVRS_P

[NFGas_MT_H]
Usar=NFGas_SVRS_H

[NFGas_PA_P]
Usar=NFGas_SVAN_P

[NFGas_PA_H]
Usar=NFGas_SVAN_H

[NFGas_PB_P]
Usar=NFGas_SVRS_P

[NFGas_PB_H]
Usar=NFGas_SVRS_H

[NFGas_PE_P]
Usar=NFGas_SVRS_P

[NFGas_PE_H]
Usar=NFGas_SVRS_H

[NFGas_PI_P]
Usar=NFGas_SVRS_P

[NFGas_PI_H]
Usar=NFGas_SVRS_H

[NFGas_PR_P]
Usar=NFGas_SVRS_P

[NFGas_PR_H] 
Usar=NFGas_SVRS_H

[NFGas_RJ_P]
Usar=NFGas_SVRS_P

[NFGas_RJ_H]
Usar=NFGas_SVRS_H

[NFGas_RN_P]
Usar=NFGas_SVRS_P

[NFGas_RN_H]
Usar=NFGas_SVRS_H

[NFGas_RO_P]
Usar=NFGas_SVRS_P

[NFGas_RO_H]
Usar=NFGas_SVRS_H

[NFGas_RS_P]
Usar=NFGas_SVRS_P

[NFGas_RS_H]
Usar=NFGas_SVRS_H

[NFGas_RR_P]
Usar=NFGas_SVRS_P

[NFGas_RR_H]
Usar=NFGas_SVRS_H

[NFGas_SC_P]
Usar=NFGas_SVRS_P

[NFGas_SC_H]
Usar=NFGas_SVRS_H

[NFGas_SE_P]
Usar=NFGas_SVRS_P

[NFGas_SE_H]
Usar=NFGas_SVRS_H

[NFGas_SP_P]
Usar=NFGas_SVRS_P

[NFGas_SP_H]
Usar=NFGas_SVRS_H

[NFGas_TO_P]
Usar=NFGas_SVRS_P

[NFGas_TO_H]
Usar=NFGas_SVRS_H

[NFGas_SVRS_P]
URL-QRCode_1.00=https://dfe-portal.svrs.rs.gov.br/nfgas/qrCode
URL-ConsultaNFGas_1.00=https://dfe-portal.svrs.rs.gov.br/nfgas/Consulta
;
NFGasRecepcao_1.00=https://nfgas.svrs.rs.gov.br/WS/NFGasRecepcao/NFGasRecepcao.asmx
NFGasRecepcaoEvento_1.00=https://nfgas.svrs.rs.gov.br/WS/NFGasRecepcaoEvento/NFGasRecepcaoEvento.asmx
NFGasConsulta_1.00=https://nfgas.svrs.rs.gov.br/WS/NFGasConsulta/NFGasConsulta.asmx
NFGasStatusServico_1.00=https://nfgas.svrs.rs.gov.br/WS/NFGasStatusServico/NFGasStatusServico.asmx

[NFGas_SVRS_H]
URL-QRCode_1.00=https://dfe-portal.svrs.rs.gov.br/nfgas/qrCode
URL-ConsultaNFGas_1.00=https://dfe-portal.svrs.rs.gov.br/nfgas/Consulta
;
NFGasRecepcao_1.00=https://nfgas-homologacao.svrs.rs.gov.br/WS/NFGasRecepcao/NFGasRecepcao.asmx
NFGasRecepcaoEvento_1.00=https://nfgas-homologacao.svrs.rs.gov.br/WS/NFGasRecepcaoEvento/NFGasRecepcaoEvento.asmx
NFGasConsulta_1.00=https://nfgas-homologacao.svrs.rs.gov.br/WS/NFGasConsulta/NFGasConsulta.asmx
NFGasStatusServico_1.00=https://nfgas-homologacao.svrs.rs.gov.br/WS/NFGasStatusServico/NFGasStatusServico.asmx
