[EVENTO]
idLote=1
; xxx varia de 001 até 999
[EVENTOxxx]
chBPe=<chave do BPe>
cOrgao=<UF do emitente>
CNPJ=<CNPJ do emitente>
dhEvento=<data e hora do evento>
tpEvento=110117
nSeqEvento=1
nProt=<numero do protocolo de autorização do BPe>
qBagagem=<quantidade de bagagens>
vTotBag=<valor total de bagagens>
vTotDFe=<valor total do DFe>
