[EVENTO]
idLote=1
; xxx varia de 001 até 999
[EVENTOxxx]
chBPe=<chave do BPe>
cOrgao=<UF do emitente>
CNPJ=<CNPJ do emitente>
dhEvento=<data e hora do evento>
tpEvento=110300
nSeqEvento=1
nProt=<numero do protocolo de autorização do BPe>
nPag=<numero do pagamento>
idTransacao=<identificador da transação>
tpMeioPgto=<tipo de meio de pagamento>
CNPJReceb=<CNPJ do recebedor>
CNPJBasePSP=<CNPJ da base do PSP>
